### ISSUE TITLE
Tutorial needs update (also the repo)

### ISSUE THREAD

**Issue by Sendoushi** [EngoEngine/TrafficManager#6]
I've been trying out the tutorial and been catching a lot of errors.
Maybe it is a breaking API?
Instead creating issues one by one, I decided to create this global issue because it seems that it won't be that few.

Anyway here is a subset of the errors that I've been getting: 
- Step 1 related:
  - [ ] https://github.com/EngoEngine/TrafficManager/issues/4
  - [ ] https://github.com/EngoEngine/TrafficManager/issues/5
  - [ ] undefined: engo.RenderSystem
  - [ ] engo.Files.Image undefined (type *engo.Formats has no field or method Image)
  - [ ] undefined: engo.NewRenderComponent
  - [ ] undefined: engo.Keys
  - [ ] undefined: engo.MouseSystem
  - [ ] undefined: engo.MouseComponent
  - [ ] undefined: MouseTracker
  - [ ] RenderSystem should be added before MouseSystem https://github.com/EngoEngine/engo/issues/318
  - [ ] undefined: engo.NewKeyboardScroller
  - [ ] too many arguments in call to common.NewKeyboardScroller

**Comment by EtienneBruines** [comment]
> Maybe it is a breaking API?

Yeah, `engo` has been changed a lot the past few weeks. This repo has been "behind" because of it; takes a lot of time, changing all branches for each update. 

See also https://github.com/EngoEngine/engo/issues/262.

**Comment by EtienneBruines** [comment]
* `engo.RenderSystem` is simply renamed/moved to `common.RenderSystem`. 
* `engo.NewRenderComponent` has become `common.RenderComponent`, where you simply define the members/variables you want (instead of passing them as arguments). So no "initializer". 
* `engo.Files.Add` (#4) - We now have `engo.Files.Load` (which returns an `error` you should check for), or `engo.Files.LoadMany` (which takes multiple strings as input). We may want to merge this into just one `Load` method (and allow for 0-99999 strings), feel free to create an issue for that. 
* `engo.RenderComponent` is `common.RenderComponent` (#5). 
* ` engo.Files.Image undefined`. Yeah, this one is a bit trickier. Taken from https://github.com/EngoEngine/engo/blob/master/demos/pong/pong.go#L65-L68, this is how we currently use preloaded textures:

```go
    ballTexture, err := common.PreloadedSpriteSingle("ball.png")
	if err != nil {
		log.Println("Could not load texture:", err)
	}
```

The name `PreloadedSpriteSingle` is a bit weird, so we should change it (dunno if there's an issue for it, there should be, because the name is horrible as @otraore mentioned). 

Looking at the definition of it at https://github.com/EngoEngine/engo/blob/master/common/render_filetype.go#L134-L146, this is how one usually uses preloaded stuff:

```go
// PreloadedSpriteSingle loads the texture-reference from `engo.Files`, and wraps it in a `*Texture`.
// This method is intended for image-files which represent entire sprites.
func PreloadedSpriteSingle(url string) (*Texture, error) {
	res, err := engo.Files.Resource(url)
	if err != nil {
		return nil, err
	}

	img, ok := res.(TextureResource)
	if !ok {
		return nil, fmt.Errorf("resource not of type `TextureResource`: %s", url)
	}

	return &Texture{img.Texture, img.Width, img.Height, engo.AABB{Max: engo.Point{1.0, 1.0}}}, nil
}
```

So one calls `engo.Files.Resource(url)`, checks for the error, casts that to the correct resource-type (also checking for error, instead of allowing `panic`), and then you can use whatever is defined within the `Resource`.
